font_size 30

# for themes
allow_remote_control yes
# default theme
include ~/.config/kitty/themes/koda.conf

font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

window_padding_width 4
enable_audio_bell no

sync_to_monitor no


repaint_delay 8
input_delay 2

#hide_window_decorations titlebar-and-corners

background_opacity 0.85
background_blur 63 
# 0 - 64 

hide_window_decorations yes

map cmd+ctrl+1 set-colors --all ~/.config/kitty/theme/color.conf
map cmd+ctrl+2 set-colors --all ~/.config/kitty/theme/koda.conf

cursor_blink_interval 0

#tab_bar_style hidden
tab_bar_edge bottom
tab_bar_min_tabs 1
tab_bar_style powerline 



cursor_smooth_move yes

cursor_trail 10
cursor_trail_decay 0.01 0.05
cursor_trail_start_threshold 0

tab_title_template "{fmt.fg._5c6370}{fmt.bg.default}  {fmt.fg._abb2bf}{fmt.bg._5c6370}  {tab.active_wd_basename}  {fmt.fg._5c6370}{fmt.bg.default}  "
active_tab_title_template "{fmt.fg._baa0e8}{fmt.bg.default}  {fmt.fg.default}{fmt.bg._baa0e8}  {tab.active_wd_basename}  {fmt.fg._baa0e8}{fmt.bg.default}  "
active_tab_font_style bold

shell_integration no-cursor

# OS specific
macos_option_as_alt left
macos_show_window_title_in window
macos_quit_when_last_window_closed yes


kitty_mod ctrl+shift
clear_all_shortcuts yes

# os_window_close
confirm_os_window_close 0
macos_quit_when_last_window_closed yes

# General
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
map cmd+q quit
map cmd+m minimize_macos_window
map cmd+h hide_macos_app
map cmd+, edit_config_file
map ctrl+cmd+, load_config_file
map ctrl+w change_font_size all +2.0
map ctrl+q change_font_size all -2.0
map cmd+0 change_font_size all 0
map cmd+shift+ctrl+e kitten unicode_input



# Window
map kitty_mod+enter launch --location=split --cwd=current
map cmd+w close_window
map kitty_mod+o close_other_windows_in_tab

# Tab
map cmd+t launch --type=tab --cwd=current
map cmd+shift+t new_tab
map kitty_mod+w close_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

