font_size 30

font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

window_padding_width 4
enable_audio_bell no

hide_window_decorations titlebar-and-corners

#repaint_delay 10
#input_delay 1
#sync_to_monitor yes

foreground              #b0b0b0
background              #101010

selection_foreground    #b0b0b0
selection_background    #272727

cursor                  #b0b0b0
cursor_text_color       #101010

url_color               #8ebeec

active_border_color     #272727
inactive_border_color   #272727


# ───────── ANSI

# black / base
color0   #000000
color8   #3d3d3d

# red / danger
color1   #4a4a4a
color9   #686868

# green
color2   #5c5c5c
color10  #a6a6a6

# yellow / warning
color3   #666666
color11  #b0b0b0

# blue / highlight
color4   #707070
color12  #b8b8b8

# magenta / pink
color5   #7a7a7a
color13  #d0d0d0

# cyan
color6   #848484
color14  #c0c0c0

# white / fg
color7   #a6a6a6
color15  #e0e0e0


cursor_blink_interval 0

tab_bar_edge bottom
tab_bar_min_tabs 1
tab_bar_style powerline 



cursor_smooth_move yes

cursor_trail 10
cursor_trail_decay 0.01 0.05
cursor_trail_start_threshold 0

tab_title_template "{fmt.fg._5c6370}{fmt.bg.default}  {fmt.fg._abb2bf}{fmt.bg._5c6370}  {tab.active_wd_basename}  {fmt.fg._5c6370}{fmt.bg.default}  "
active_tab_title_template "{fmt.fg._baa0e8}{fmt.bg.default}  {fmt.fg.default}{fmt.bg._baa0e8}  {tab.active_wd_basename}  {fmt.fg._baa0e8}{fmt.bg.default}  "
active_tab_font_style bold

shell_integration no-cursor

# OS specific
macos_option_as_alt left
macos_show_window_title_in window


kitty_mod ctrl+shift
clear_all_shortcuts yes

# os_window_close
confirm_os_window_close 0
macos_quit_when_last_window_closed yes

# General
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard
map cmd+q quit
map cmd+m minimize_macos_window
map cmd+h hide_macos_app
map cmd+, edit_config_file
map ctrl+cmd+, load_config_file
map ctrl+w change_font_size all +2.0
map ctrl+q change_font_size all -2.0
map cmd+0 change_font_size all 0
map cmd+shift+ctrl+e kitten unicode_input



# Window
map kitty_mod+enter launch --location=split --cwd=current
map cmd+w close_window
map kitty_mod+o close_other_windows_in_tab

# Tab
map cmd+t launch --type=tab --cwd=current
map cmd+shift+t new_tab
map kitty_mod+w close_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7

