#!/usr/bin/env sh

killall borders 2>/dev/null

start_borders() {
    borders active_color=0xfff2f2f2 \
            inactive_color=0xff333333 \
            width=3.0 \
            flash_duration=0.2 \
            hidpi=on \
            style=square \
            radius=0.0 &
}

start_borders

yabai -m config layout bsp
yabai -m config window_placement second-child

yabai -m config top_padding 16
yabai -m config bottom_padding 16
yabai -m config left_padding 16
yabai -m config right_padding 16
yabai -m config window_gap 16

yabai -m config window_opacity off
yabai -m config window_shadow off
yabai -m config window_border off

yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier fn
yabai -m config mouse_action move
yabai -m config mouse_drop_action resize


yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Terminal$" manage=off

yabai -m signal --add event=window_focused action='
    curr_app=$(yabai -m query --windows --window | jq -r ".app")
    if [ "$curr_app" = "kitty" ]; then
        borders radius=0.0 style=square
    else
        borders radius=12.0 style=round
    fi
'
